// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk7vur0nRByrTgtEeMSeNBeohdlePTHrA',
    appId: '1:188563736527:web:28aa9e95c7391c8748f4ba',
    messagingSenderId: '188563736527',
    projectId: 'mi-app-segura-54820',
    authDomain: 'mi-app-segura-54820.firebaseapp.com',
    storageBucket: 'mi-app-segura-54820.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfaFwBxCeOL4VrcWY8tBMbmY-ZPw4wqtk',
    appId: '1:188563736527:android:efb15faa876ea80748f4ba',
    messagingSenderId: '188563736527',
    projectId: 'mi-app-segura-54820',
    storageBucket: 'mi-app-segura-54820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-KEgHdcKJ2PLYomDhkWUa_L9bim3qB4',
    appId: '1:188563736527:ios:d2d875ff95adf15d48f4ba',
    messagingSenderId: '188563736527',
    projectId: 'mi-app-segura-54820',
    storageBucket: 'mi-app-segura-54820.firebasestorage.app',
    iosBundleId: 'com.secureapp.ghostClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz-KEgHdcKJ2PLYomDhkWUa_L9bim3qB4',
    appId: '1:188563736527:ios:d2d875ff95adf15d48f4ba',
    messagingSenderId: '188563736527',
    projectId: 'mi-app-segura-54820',
    storageBucket: 'mi-app-segura-54820.firebasestorage.app',
    iosBundleId: 'com.secureapp.ghostClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk7vur0nRByrTgtEeMSeNBeohdlePTHrA',
    appId: '1:188563736527:web:7dd162b09208fda548f4ba',
    messagingSenderId: '188563736527',
    projectId: 'mi-app-segura-54820',
    authDomain: 'mi-app-segura-54820.firebaseapp.com',
    storageBucket: 'mi-app-segura-54820.firebasestorage.app',
  );
}
